/*
 Navicat Premium Data Transfer

 Source Server         : 1.14.62.248
 Source Server Type    : MySQL
 Source Server Version : 80200 (8.2.0)
 Source Host           : 1.14.62.248:3306
 Source Schema         : yzxxw_management

 Target Server Type    : MySQL
 Target Server Version : 80200 (8.2.0)
 File Encoding         : 65001

 Date: 17/03/2026 19:47:24
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for homepage_themes
-- ----------------------------
DROP TABLE IF EXISTS `homepage_themes`;
CREATE TABLE `homepage_themes` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主题ID',
  `theme_name` varchar(50) COLLATE utf8mb4_general_ci NOT NULL COMMENT '主题名称（如：普通）',
  `theme_style` json NOT NULL COMMENT '主题样式配置（JSON格式，包含颜色、字体、背景等CSS规则）',
  `is_default` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为默认主题',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态: 1=启用, 0=禁用',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_default` (`is_default`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='主题配置表';

-- ----------------------------
-- Records of homepage_themes
-- ----------------------------
BEGIN;
INSERT INTO `homepage_themes` (`id`, `theme_name`, `theme_style`, `is_default`, `status`, `created_at`, `updated_at`) VALUES (1, '普通主题', '{\"colors\": {\"error\": \"#EF4444\", \"border\": \"#E8EEF7\", \"primary\": \"#2E5BBA\", \"success\": \"#10B981\", \"surface\": \"#FFFFFF\", \"warning\": \"#F59E0B\", \"scanBtnBg\": \"#FFFFFF\", \"background\": \"#F5F7FA\", \"primaryDark\": \"#1E3D7A\", \"textPrimary\": \"#0F1729\", \"primaryLight\": \"#5B8BE8\", \"textSecondary\": \"#6B7D9B\"}, \"tabBar\": {\"selectedColor\": \"#2E5BBA\", \"backgroundColor\": \"#FFFFFF\"}, \"shadows\": {\"card\": \"0 8rpx 32rpx rgba(46, 91, 186, 0.08)\", \"primary\": \"0 4rpx 20rpx rgba(46, 91, 186, 0.08)\", \"primaryStrong\": \"0 6rpx 20rpx rgba(46, 91, 186, 0.3)\"}, \"themeId\": \"normal\", \"gradients\": {\"card\": \"linear-gradient(135deg, #FAFBFC 0%, #F5F8FC 100%)\", \"primary\": \"linear-gradient(135deg, #2E5BBA 0%, #5B8BE8 100%)\", \"surface\": \"linear-gradient(135deg, #FFFFFF 0%, #F8FAFF 100%)\", \"background\": \"linear-gradient(180deg, #E8EEF7 0%, #F5F7FA 50%, #FAFBFC 100%)\"}, \"themeIcon\": \"🎨\", \"themeName\": \"普通主题\", \"imageFilter\": \"none\", \"tabBarIcons\": {\"home\": {\"iconPath\": \"/static/home.png\", \"selectedIconPath\": \"/static/home-selected.png\"}, \"live\": {\"iconPath\": \"/static/live.png\", \"selectedIconPath\": \"/static/live-selected.png\"}, \"user\": {\"iconPath\": \"/static/user.png\", \"selectedIconPath\": \"/static/user-selected.png\"}, \"class\": {\"iconPath\": \"/static/class.png\", \"selectedIconPath\": \"/static/class-selected.png\"}, \"course\": {\"iconPath\": \"/static/course.png\", \"selectedIconPath\": \"/static/course-selected.png\"}}, \"navigationBar\": {\"textStyle\": \"white\", \"backgroundColor\": \"#2E5BBA\"}}', 1, 1, '2026-03-13 11:10:53', '2026-03-17 18:25:21');
INSERT INTO `homepage_themes` (`id`, `theme_name`, `theme_style`, `is_default`, `status`, `created_at`, `updated_at`) VALUES (2, '哀悼主题', '{\"colors\": {\"error\": \"#EF4444\", \"border\": \"#E0E0E0\", \"primary\": \"#333333\", \"success\": \"#10B981\", \"surface\": \"#FFFFFF\", \"tagText\": \"#FFFFFF\", \"warning\": \"#F59E0B\", \"scanBtnBg\": \"#333333\", \"tagTypeBg\": \"linear-gradient(135deg, #666666 0%, #444444 100%)\", \"background\": \"#F5F5F5\", \"primaryDark\": \"#1A1A1A\", \"tagStatusBg\": \"rgba(51, 51, 51, 0.85)\", \"textPrimary\": \"#1A1A1A\", \"primaryLight\": \"#555555\", \"tagTypeShadow\": \"0 2rpx 12rpx rgba(102, 102, 102, 0.4)\", \"textSecondary\": \"#666666\", \"tagClassTypeBg\": \"linear-gradient(135deg, #888888 0%, #666666 100%)\", \"tagClassTypeColor\": \"#FFFFFF\", \"tagClassTypeShadow\": \"0 2rpx 8rpx rgba(102, 102, 102, 0.3)\"}, \"tabBar\": {\"selectedColor\": \"#333333\", \"backgroundColor\": \"#FFFFFF\"}, \"filters\": {\"tagFilter\": \"grayscale(100%)\"}, \"shadows\": {\"card\": \"0 8rpx 32rpx rgba(51, 51, 51, 0.08)\", \"primary\": \"0 4rpx 20rpx rgba(51, 51, 51, 0.08)\", \"primaryStrong\": \"0 6rpx 20rpx rgba(51, 51, 51, 0.3)\"}, \"themeId\": \"mourning\", \"gradients\": {\"card\": \"linear-gradient(135deg, #FAFAFA 0%, #F5F5F5 100%)\", \"primary\": \"linear-gradient(135deg, #333333 0%, #555555 100%)\", \"surface\": \"linear-gradient(135deg, #FFFFFF 0%, #F8F8F8 100%)\", \"background\": \"linear-gradient(180deg, #E8E8E8 0%, #F5F5F5 50%, #FAFAFA 100%)\"}, \"themeName\": \"哀悼主题\", \"imageFilter\": \"grayscale(100%)\", \"tabBarIcons\": {\"home\": {\"iconPath\": \"/static/tabBar/mourning/home.png\", \"selectedIconPath\": \"/static/home.png\"}, \"live\": {\"iconPath\": \"/static/tabBar/mourning/live.png\", \"selectedIconPath\": \"/static/live.png\"}, \"user\": {\"iconPath\": \"/static/tabBar/mourning/user.png\", \"selectedIconPath\": \"/static/user.png\"}, \"class\": {\"iconPath\": \"/static/tabBar/mourning/class.png\", \"selectedIconPath\": \"/static/class.png\"}, \"course\": {\"iconPath\": \"/static/tabBar/mourning/course.png\", \"selectedIconPath\": \"/static/course.png\"}}, \"navigationBar\": {\"textStyle\": \"white\", \"backgroundColor\": \"#333333\"}}', 0, 0, '2026-03-13 11:11:28', '2026-03-17 18:09:42');
INSERT INTO `homepage_themes` (`id`, `theme_name`, `theme_style`, `is_default`, `status`, `created_at`, `updated_at`) VALUES (3, '党建主题', '{\"colors\": {\"error\": \"#DC2626\", \"accent\": \"#D4AF37\", \"border\": \"#FFE4E4\", \"primary\": \"#C41E3A\", \"success\": \"#10B981\", \"surface\": \"#FFFFFF\", \"warning\": \"#D4AF37\", \"scanBtnBg\": \"#C41E3A\", \"background\": \"#FFFAFA\", \"accentLight\": \"#E8C547\", \"primaryDark\": \"#9B1B30\", \"textPrimary\": \"#1A1A1A\", \"primaryLight\": \"#E63946\", \"textSecondary\": \"#666666\"}, \"tabBar\": {\"selectedColor\": \"#C41E3A\", \"backgroundColor\": \"#FFFFFF\"}, \"shadows\": {\"card\": \"0 8rpx 32rpx rgba(196, 30, 58, 0.1)\", \"accent\": \"0 4rpx 16rpx rgba(212, 175, 55, 0.3)\", \"primary\": \"0 4rpx 20rpx rgba(196, 30, 58, 0.12)\", \"primaryStrong\": \"0 6rpx 24rpx rgba(196, 30, 58, 0.25)\"}, \"themeId\": \"party\", \"gradients\": {\"card\": \"linear-gradient(135deg, #FFFFFF 0%, #FFF8F8 100%)\", \"accent\": \"linear-gradient(135deg, #D4AF37 0%, #E8C547 100%)\", \"header\": \"linear-gradient(135deg, #C41E3A 0%, #9B1B30 100%)\", \"primary\": \"linear-gradient(135deg, #C41E3A 0%, #E63946 50%, #C41E3A 100%)\", \"surface\": \"linear-gradient(135deg, #FFFFFF 0%, #FFFBFB 100%)\", \"background\": \"linear-gradient(180deg, #FFF0F0 0%, #FFFAFA 40%, #FFFFFF 100%)\"}, \"themeName\": \"党建主题\", \"imageFilter\": \"none\", \"tabBarIcons\": {\"home\": {\"iconPath\": \"/static/home.png\", \"selectedIconPath\": \"/static/tabBar/party/home-selected.png\"}, \"live\": {\"iconPath\": \"/static/live.png\", \"selectedIconPath\": \"/static/tabBar/party/live-selected.png\"}, \"user\": {\"iconPath\": \"/static/user.png\", \"selectedIconPath\": \"/static/tabBar/party/user-selected.png\"}, \"class\": {\"iconPath\": \"/static/class.png\", \"selectedIconPath\": \"/static/tabBar/party/class-selected.png\"}, \"course\": {\"iconPath\": \"/static/course.png\", \"selectedIconPath\": \"/static/tabBar/party/course-selected.png\"}}, \"navigationBar\": {\"textStyle\": \"white\", \"backgroundColor\": \"#C41E3A\"}}', 0, 0, '2026-03-13 11:15:36', '2026-03-17 17:23:12');
INSERT INTO `homepage_themes` (`id`, `theme_name`, `theme_style`, `is_default`, `status`, `created_at`, `updated_at`) VALUES (4, '喜庆节日主题', '{\"colors\": {\"error\": \"#FF5252\", \"accent\": \"#FFD700\", \"border\": \"#FFD6D6\", \"primary\": \"#FF0000\", \"success\": \"#4CAF50\", \"surface\": \"#FFFFFF\", \"warning\": \"#FFD700\", \"scanBtnBg\": \"#FF0000\", \"secondary\": \"#FF4444\", \"background\": \"#FFF5F5\", \"accentLight\": \"#FFE44D\", \"primaryDark\": \"#CC0000\", \"textPrimary\": \"#2D2D2D\", \"primaryLight\": \"#FF3333\", \"textSecondary\": \"#666666\"}, \"tabBar\": {\"selectedColor\": \"#FF0000\", \"backgroundColor\": \"#FFFFFF\"}, \"shadows\": {\"card\": \"0 8rpx 32rpx rgba(255, 0, 0, 0.12)\", \"accent\": \"0 4rpx 16rpx rgba(255, 215, 0, 0.35)\", \"primary\": \"0 4rpx 20rpx rgba(255, 0, 0, 0.15)\", \"primaryStrong\": \"0 6rpx 24rpx rgba(255, 0, 0, 0.3)\"}, \"themeId\": \"festival\", \"gradients\": {\"card\": \"linear-gradient(135deg, #FFFFFF 0%, #FFF8F8 100%)\", \"accent\": \"linear-gradient(135deg, #FFD700 0%, #FFE44D 100%)\", \"header\": \"linear-gradient(135deg, #FF0000 0%, #FF3333 50%, #FF6666 100%)\", \"festive\": \"linear-gradient(135deg, #FF4444 0%, #FF0000 50%, #FFD700 100%)\", \"primary\": \"linear-gradient(135deg, #FF0000 0%, #FF3333 50%, #FF6666 100%)\", \"surface\": \"linear-gradient(135deg, #FFFFFF 0%, #FFFAFA 100%)\", \"background\": \"linear-gradient(180deg, #FFF0F0 0%, #FFF5F5 40%, #FFFFFF 100%)\"}, \"themeName\": \"喜庆节日主题\", \"imageFilter\": \"none\", \"tabBarIcons\": {\"home\": {\"iconPath\": \"/static/home.png\", \"selectedIconPath\": \"/static/tabBar/festival/home-selected.png\"}, \"live\": {\"iconPath\": \"/static/live.png\", \"selectedIconPath\": \"/static/tabBar/festival/live-selected.png\"}, \"user\": {\"iconPath\": \"/static/user.png\", \"selectedIconPath\": \"/static/tabBar/festival/user-selected.png\"}, \"class\": {\"iconPath\": \"/static/class.png\", \"selectedIconPath\": \"/static/tabBar/festival/class-selected.png\"}, \"course\": {\"iconPath\": \"/static/course.png\", \"selectedIconPath\": \"/static/tabBar/festival/course-selected.png\"}}, \"navigationBar\": {\"textStyle\": \"white\", \"backgroundColor\": \"#FF0000\"}}', 0, 0, '2026-03-13 11:22:07', '2026-03-17 18:25:21');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
